### ISSUE TITLE
Revamp of Backend Directory Structure. 

### ISSUE THREAD

**Issue by GKephart** [Deep-Dive-Coding-Fullstack-Licensing/example-capstone#4]
After two iterations of the current backend curriculum, it has become apparent that a major refactor of the express directory structure is in order. The current directory structure is unwieldy, and it has become hard to understand how certain files relate to each other. The main reason for this is  We currently house the routes, controllers, and validators in their own separate directories. Instead the files should be split up by endpoint/feature so that all the controllers, routes and validators for a database entity or feature  are housed together in a directory named after the entity or route in question. 

**Here  are some of  the benefits of making this change:** 

* it will enable for a directory structure that better matches how the rest endpoints are laid out. 
* The backend directory structure will more closely align with the frontend directory structure
* It is more apparent how files relate to each other. 
Below is a mockup of what this would look like. 
 \
![image](https://user-images.githubusercontent.com/14102597/93927609-5e172f00-fcd6-11ea-9674-138fcafe02ea.png)

Some other minor directory structure changes will also be introduced. Mainly reintroducing an App.ts in the frontend and having the store configured in `/frontend/src/store/index.js` instead of `/frontend/src/index.js`.

**Comment by Unitoch** [comment]
Thanks, I agree with the reasoning here and think it's a good idea.  I'm guessing this will not be backwards compatible, right?  We should probably iterate to a 2.0 version of the app when we release this.

**Comment by GKephart** [comment]
Closing old issue
